//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service()
        {
            this.activityTimes = new HashSet<activityTime>();
        }
    
        public int serviceId { get; set; }
        public int categoryId { get; set; }
        public string serviceName { get; set; }
        public int businessId { get; set; }
        public bool kindOfPermission { get; set; }
        public Nullable<int> limitDays { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activityTime> activityTimes { get; set; }
        public virtual business business { get; set; }
        public virtual category category { get; set; }
    }
}
