//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class unusual
    {
        public int unusualId { get; set; }
        public double average { get; set; }
        public int activityTimeId { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<double> StandardDeviation { get; set; }
        public Nullable<bool> kindOfUnusual { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual activityTime activityTime { get; set; }
    }
}
