//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class customersInLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customersInLine()
        {
            this.ranges = new HashSet<ranges>();
            this.swaps = new HashSet<swaps>();
        }
    
        public int TurnId { get; set; }
        public int custId { get; set; }
        public int activityTimeId { get; set; }
        public Nullable<System.TimeSpan> enterHour { get; set; }
        public Nullable<System.TimeSpan> estimatedHour { get; set; }
        public Nullable<System.TimeSpan> ActualHour { get; set; }
        public int preAlert { get; set; }
        public bool statusTurn { get; set; }
    
        public virtual activityTimes activityTimes { get; set; }
        public virtual customers customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ranges> ranges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<swaps> swaps { get; set; }
    }
}
